p8105_hw2_zc2822
================
Zhengyong Chen

## Problem 1

Read and clean the data:

``` r
subway_df = 
  read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  select(line:entry, vending, ada) |> 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

The datasets contain variables line, station_name, station_latitude,
station_longitude, route1, route2, route3, route4, route5, route6,
route7, route8, route9, route10, route11, entrance_type, entry, vending,
ada, the dimension is 1868 \* 19.

How many distinct stations are there?

``` r
subway_df |> 
  select(line, station_name) |> 
  distinct() |> 
  nrow()
```

    ## [1] 465

How many stations are ADA compliant?

``` r
subway_df |> 
  filter(ada == TRUE) |> 
  select(line, station_name) |> 
  distinct() |> 
  nrow()
```

    ## [1] 84

What proportion of station entrances / exits without vending allow
entrance?

``` r
novending_entry = 
  subway_df |> 
  filter(vending == "NO", entry == TRUE) |> 
  nrow()

total_novending = 
  subway_df |> 
  filter(vending == "NO") |> 
  nrow()  

prop = novending_entry / total_novending
prop
```

    ## [1] 0.3770492

Reformat data so that route number and route name are distinct
variables. How many distinct stations serve the A train? Of the stations
that serve the A train, how many are ADA compliant?

``` r
subway_df_reformat =
  subway_df |> 
  mutate(across(route1:route11, as.character)) |> 
  pivot_longer(
    cols = route1:route11,
    names_to = "route_num",
    values_to = "route_name"
  ) 

A_train = 
  subway_df_reformat |> 
    filter(route_name == "A") |> 
    select(line, station_name) |> 
    distinct() |> 
    nrow()

A_train_ada = 
  subway_df_reformat |> 
    filter(route_name == "A", ada == TRUE) |> 
    select(line, station_name) |> 
    distinct() |> 
    nrow()
```

60 distinct stations serve the A train. Of the stations that serve the A
train, 17 are ADA compliant.

## Problem 2

Read and clean the Mr. Trash Wheel sheet:

``` r
mr_trash_df = 
  read_excel("data/202409\ Trash\ Wheel\ Collection\ Data.xlsx", 
                      sheet = "Mr. Trash Wheel",
                      na = c("NA", ".", ""),
                      range = "A2:N655"
                      ) |> 
  janitor::clean_names() |> 
  filter(!is.na(dumpster)) |> 
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls),
    trash_wheel = "Mr. Trash Wheel",
    year = as.numeric(year)
  ) |> 
  relocate(trash_wheel)
```

Read and clean the Professor Trash Wheel sheet:

``` r
prof_trash_df = 
  read_excel("data/202409\ Trash\ Wheel\ Collection\ Data.xlsx", 
                      sheet = "Professor Trash Wheel",
                      na = c("NA", ".", ""),
                      range = "A2:M123"
                      ) |> 
  janitor::clean_names() |> 
  filter(!is.na(dumpster)) |> 
  mutate(
    trash_wheel = "Professor Trash Wheel",
    year = as.numeric(year)
  ) |> 
  relocate(trash_wheel)
```

Read and clean the Gwynnda Trash Wheel sheet:

``` r
gwynnda_trash_df = 
  read_excel("data/202409\ Trash\ Wheel\ Collection\ Data.xlsx", 
                      sheet = "Gwynnda Trash Wheel",
                      na = c("NA", ".", ""),
                      range = "A2:L266"
                      ) |> 
  janitor::clean_names() |> 
  filter(!is.na(dumpster)) |> 
  mutate(
    trash_wheel = "Gwynnda Trash Wheel",
    year = as.numeric(year)
  ) |> 
  relocate(trash_wheel)
```

Combine the datasets:

``` r
combined_trash_df = bind_rows(mr_trash_df, prof_trash_df, gwynnda_trash_df)
```

A paragraph about these data:

The number of observations in the resulting dataset is 1033. The
variables in the datasets are trash_wheel, dumpster, month, year, date,
weight_tons, volume_cubic_yards, plastic_bottles, polystyrene,
cigarette_butts, glass_bottles, plastic_bags, wrappers, sports_balls,
homes_powered. The total weight of trash collected by Professor Trash
Wheel was 246.74. The total number of cigarette butts collected by
Gwynnda in June of 2022 was 18120.

## Problem 3

Import and clean Bakers dataset:

``` r
bakers_df = 
  read_csv("data/gbb_datasets/bakers.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  separate(baker_name, into = c("baker", "last_name")) |> 
  arrange(series) |> 
  relocate(series)
```

    ## Rows: 120 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker Name, Baker Occupation, Hometown
    ## dbl (2): Series, Baker Age
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: Expected 2 pieces. Additional pieces discarded in 10 rows [8, 20, 60, 76, 80,
    ## 90, 96, 102, 108, 110].

Import and clean Bakes dataset:

``` r
bakes_df = 
  read_csv("data/gbb_datasets/bakes.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  mutate(
    baker = ifelse(baker == '"Jo"', "Joanne", baker),
    baker = ifelse(baker == "Mary-Anne", "Mary", baker),
    baker = ifelse(baker == "Sarah-Jane", "Sarah", baker),
  )
```

    ## Rows: 548 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker, Signature Bake, Show Stopper
    ## dbl (2): Series, Episode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Import and clean Results dataset:

``` r
results_df = 
  read_csv("data/gbb_datasets/results.csv", na = c("NA", ".", ""), skip = 2) |> 
  janitor::clean_names() |> 
  mutate(
    baker = ifelse(baker == "Mary-Anne", "Mary", baker),
    baker = ifelse(baker == "Sarah-Jane", "Sarah", baker),
    baker = ifelse(baker == "Kim-Joy", "Kim", baker)
  )
```

    ## Rows: 1136 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (2): baker, result
    ## dbl (3): series, episode, technical
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Using `anti-join`:

``` r
anti_join(bakers_df, bakes_df)
```

    ## Joining with `by = join_by(series, baker)`

    ## # A tibble: 27 × 6
    ##    series baker  last_name  baker_age baker_occupation                  hometown
    ##     <dbl> <chr>  <chr>          <dbl> <chr>                             <chr>   
    ##  1      2 Jo     Wheatley          41 Housewife                         Ongar, …
    ##  2      6 Ugn    Bubnaityte        32 PA and administrator              Woodfor…
    ##  3      9 Antony Amourdoux         30 Banker                            London  
    ##  4      9 Briony Williams          33 Full-time parent                  Bristol 
    ##  5      9 Dan    Beasley           36 Full-time parent                  London  
    ##  6      9 Imelda McCarron          33 Countryside recreation officer    County …
    ##  7      9 Jon    Jenkins           47 Blood courier                     Newport 
    ##  8      9 Karen  Wright            60 In-store sampling assistant       Wakefie…
    ##  9      9 Kim    Joy               27 Mental health specialist          Leeds   
    ## 10      9 Luke   Thompson          30 Civil servant/house and techno DJ Sheffie…
    ## # ℹ 17 more rows

``` r
anti_join(bakers_df, results_df)
```

    ## Joining with `by = join_by(series, baker)`

    ## # A tibble: 2 × 6
    ##   series baker last_name  baker_age baker_occupation     hometown               
    ##    <dbl> <chr> <chr>          <dbl> <chr>                <chr>                  
    ## 1      2 Jo    Wheatley          41 Housewife            Ongar, Essex           
    ## 2      6 Ugn   Bubnaityte        32 PA and administrator Woodford, London / Vil…

Combine the datasets:

``` r
combined_gbb_df = 
  left_join(bakes_df, results_df, by = c("series", "episode", "baker")) |> 
  left_join(bakers_df, by = c("series", "baker")) 
```

Export the result as a CSV:

``` r
write_csv(combined_gbb_df, "data/gbb_datasets/combined_gbb.csv")
```

**Describe the data cleaning process**

I first imported the three datasets. There are header rows in the
Results dataset, so I applyed `skip` when using `read_csv`. Then I
looked through the variables in each dataset, where I found the bakers’
names are recorded differently. So, I separated the full name in the
Bakers dataset into the first name and the last name. Then I checked for
completeness and correctness across datasets, by viewing and using
`anti_join`, I corrected some names in the Bakes and Results. For
example, I used `ifelse` in `mutate` to replace “Jo” with Joanne. After
this, I arranged and relocated series in the Bakers dataset for easier
read. To merge the three datasets into a final one, I used `left_join`
to first join the `results_df` to the `bakes_df` by their common
variables, then I joined `bakers_df` to these two. The final dataset
`combined_gbb_df` has 11 variables, which are: series, episode, baker,
signature_bake, show_stopper, technical, result, last_name, baker_age,
baker_occupation, hometown. It has 548 rows.

**Create a reader-friendly table showing the star baker or winner of
each episode in Seasons 5 through 10:**

``` r
winner_df =
  results_df |> 
  select(series, episode, baker, result) |> 
  filter(series >= 5, series <= 10, 
         result %in% c("STAR BAKER", "WINNER")) |> 
  pivot_wider(
    names_from = series, 
    values_from = baker
    ) |> 
  relocate(result) 

winner_df
```

    ## # A tibble: 10 × 8
    ##    result     episode `5`     `6`    `7`       `8`    `9`    `10`    
    ##    <chr>        <dbl> <chr>   <chr>  <chr>     <chr>  <chr>  <chr>   
    ##  1 STAR BAKER       1 Nancy   Marie  Jane      Steven Manon  Michelle
    ##  2 STAR BAKER       2 Richard Ian    Candice   Steven Rahul  Alice   
    ##  3 STAR BAKER       3 Luis    Ian    Tom       Julia  Rahul  Michael 
    ##  4 STAR BAKER       4 Richard Ian    Benjamina Kate   Dan    Steph   
    ##  5 STAR BAKER       5 Kate    Nadiya Candice   Sophie Kim    Steph   
    ##  6 STAR BAKER       6 Chetna  Mat    Tom       Liam   Briony Steph   
    ##  7 STAR BAKER       7 Richard Tamal  Andrew    Steven Kim    Henry   
    ##  8 STAR BAKER       8 Richard Nadiya Candice   Stacey Ruby   Steph   
    ##  9 STAR BAKER       9 Richard Nadiya Andrew    Sophie Ruby   Alice   
    ## 10 WINNER          10 Nancy   Nadiya Candice   Sophie Rahul  David

There are some predictable overall winners, for example, Nadiya and
Rahul appeared mutiple times being the star baker in different episodes.
There are also surprises, for example, David did not appear to be the
star baker in any episode in series 10, but he was the winner of that
series.

**Import, clean, tidy, and organize the viewership data in viewers.csv**

``` r
viewers_df = 
  read_csv("data/gbb_datasets/viewers.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = series_1:series_10,
    names_to = "series",
    values_to = "viewers"
  ) |> 
  mutate(
    series = sub("series_", "", series),
    series = as.integer(series)
  ) |> 
  arrange(series) |> 
  relocate(series)
```

    ## Rows: 10 Columns: 11
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (11): Episode, Series 1, Series 2, Series 3, Series 4, Series 5, Series ...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
viewers_df |> head(10)
```

    ## # A tibble: 10 × 3
    ##    series episode viewers
    ##     <int>   <dbl>   <dbl>
    ##  1      1       1    2.24
    ##  2      1       2    3   
    ##  3      1       3    3   
    ##  4      1       4    2.6 
    ##  5      1       5    3.03
    ##  6      1       6    2.75
    ##  7      1       7   NA   
    ##  8      1       8   NA   
    ##  9      1       9   NA   
    ## 10      1      10   NA

What was the average viewership in Season 1? In Season 5?

``` r
viewers_season1 = 
  viewers_df |> 
  filter(series == 1) |> 
  summarise(avg_season1 = mean(viewers, na.rm = TRUE))
```

``` r
viewers_season5 = 
  viewers_df |> 
  filter(series == 5) |> 
  summarise(avg_season5 = mean(viewers, na.rm = TRUE))
```

The average viewership in Season 1 is 2.77, and in Season 5 is 10.0393.
